shell = "zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ['defer']

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ['defer']

[templates]
defer = {value = 'zsh-defer source "{{ file }}"', each = true}
