snippets:
  # git
  - name: git commit message
    keyword: gcm
    snippet: git commit -m '{{commit_message}}'
  - name: git push
    keyword: gpush
    snippet: git push origin {{branch_name}}
  - name: git pull
    keyword: gpull
    snippet: git pull origin {{branch_name}}
  - name: git checkout
    keyword: gco
    snippet: git checkout {{branch_name}}
  - name: git checkout -b
    keyword: gcb
    snippet: git checkout -b {{branch_name}}
  # docker
  - name: docker compose
    keyword: dc
    snippet: docker compose {{args}}
  # claude
  - name: claude code
    keyword: cl
    snippet: claude
  - name: continue latest claude session
    keyword: clc
    snippet: claude --continue
  - name: resume claude session
    keyword: clr
    snippet: claude --resume
  # utilities
  - name: create directory and move into it
    keyword: dir
    snippet: mkdir {{dir_name}} && cd "$_"
  - name: navigate to projects directory
    keyword: i
    snippet: cd ~/i && cd {{project_name}}
  - name: navigate to experiments directory
    keyword: x
    snippet: cd ~/x && cd {{experiment_name}}
  - name: search cloned repositories
    keyword: sr
    snippet: cd $(ghq list -p | fzf)
