name: Auto-update flake.lock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00
jobs:
  update-flake-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-nix
        with:
          cachixAuthToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: true
      - name: Update flake.lock
        run: nix flake update
      - name: Create GitHub App token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ vars.PULL_REQUEST_APP_ID }}
          private-key: ${{ secrets.PULL_REQUEST_APP_PRIVATE_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          sign-commits: true
          commit-message: "chore(flake): update dependencies"
          title: "chore(flake): update flake.lock"
