name: Build nix
on:
  push:
    branches: ["main"]
    paths:
      - '**.nix'
      - flake.lock
      - .github/workflows/build-nix.yml
      - .github/actions/setup-nix/**
jobs:
  build-macos:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-nix
        with:
          cachixAuthToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: false
      - name: Build devshell
        run: nix develop --show-trace -c true
      - name: Build nix-darwin and home-manager configurations
        run: nix build --show-trace --no-link .#darwinConfigurations.gabi.system
      - name: Print disk usage
        run: df -h
