name: Check
on:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./.github/actions/setup-nix
        with:
          skipPush: true
      - name: Run formatter
        run: nix fmt -- --ci
      - name: Run linter
        run: nix flake check --show-trace
