name: Check
on:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup-nix
        with:
          skipPush: true
      - name: Run formatter
        run: nix fmt -- --ci
      - name: Run linter
        run: nix flake check --show-trace
