name: "Nix build"
on:
  push:
    branches: ["main"]
    paths:
      - '**.nix'
      - flake.lock
jobs:
  build-macos:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-nix
        with:
          cachixAuthToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: false
      - name: Build devshell
        run: nix develop --show-trace -c true
      - name: Build nix-darwin and home-manager configurations
        run: nix build --show-trace --no-link .#darwinConfigurations.gabi.system
      - name: Print disk usage
        run: df -h
