name: "Nix build"
on:
  push:
    branches: ["main"]
    paths:
      - nix/**
      - flake.nix
      - flake.lock
  pull_request:
jobs:
  build-macos:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
        with:
          name: kazukit
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: "ryoppippi,nix-community"
      - name: Build devshell
        run: nix develop --show-trace -c true
      - name: Build nix-darwin and home-manager configurations
        run: nix build --show-trace --no-link .#darwinConfigurations.gabi.system
